- hosts: localhost
  become: true
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
  tasks:
    - include: tasks/zsh.yml
    - include: tasks/node.yml
    - include: tasks/bspwm.yml
    - include: tasks/polybar.yml
    - include: tasks/neovim.yml
    - include: tasks/tmux.yml
    - include: tasks/kitty.yml
    - include: tasks/npm-packages.yml
    - include: tasks/brave.yml
    - include: tasks/git.yml
